[package]
name = "nano-id"
version = "0.0.1"
authors = ["Fangdun Tsai <cfddream@gmail.com>"]
description = "A tiny, secure, URL-friendly, unique string ID generator for Rust"
documentation = "https://docs.rs/nano-id"
repository = "https://github.com/viz-rs/nano-id"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[features]
default = ["base64"]

base64 = []
base62 = []
base58 = []

step = []

[dependencies]
getrandom = "0.2.2"
